### ISSUE TITLE
Confic with Yii 2 File Kit extendsion

### ISSUE THREAD

**Issue by dungphanxuan** [kartik-v/yii2-number#1]
## Prerequisites

 i try to setup so Yii 2 File Kit upload not working
## Steps to reproduce the issue

1. Add Widget
2. Run update
3. Not work

## Expected behavior and actual behavior

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/10725732/36016976-3ffd1874-0da8-11e8-96dc-349593e73bd5.png)

I was expecting...

#### Browsers

- [ x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-number version:
- yii2-file-kit

**Comment by kartik-v** [comment]
Sorry - wrong repo - not related to this extension... you need to check your code and cross check with the other extension developer.
