### ISSUE TITLE
 Unable to enter negative values ​​with suffix

### ISSUE THREAD

**Issue by Mark1161993** [kartik-v/yii2-number#14]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-number.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/number).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create new NumberControl input with a suffix. Example:
`'maskedInput' => ['suffix' => ' €']`
2. Use js to set a negative number value. Example:
`$('#myId-disp').inputmask("setvalue", -2);`

## Expected behavior and actual behavior

When I follow those steps, I see the number '0' appear in field and not the number chosen. If I try with a positive number everything works correctly. If I try with a prefix everything works correctly

## Environment
- Apache server
- PHP 7.2.13

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.4.1
- yii2-number version: last dev-master

## Isolating the problem

- [ ] This bug happens [on the docs and demos page](https://demos.krajee.com/number)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-number without other plugins.

**Comment by ramssesable** [comment]
I have the same issue

**Comment by leandrodsn** [comment]
The same behavior happens to me

**Comment by tholag** [comment]
It seems to be a bug in the underlying input-mask, see this issue:
[https://github.com/RobinHerbots/Inputmask/issues/1500](https://github.com/RobinHerbots/Inputmask/issues/1500)

Adding a placeholder fixed the issue of not being able to display negative numbers when a suffix was assigned for me:
```
    'maskedInputOptions' => [
        'suffix' => ' €',
        'groupSeparator' => '.',
        'radixPoint' => ',',
        'allowMinus' => true,
        'digits' => 2,
        'rightAlign' => true,
        /* BUGFIX: */
        'placeholder' => '0', 
    ],
```
