### ISSUE TITLE
Two inputs showing with new Yii2 Version

### ISSUE THREAD

**Issue by crimson-med** [kartik-v/yii2-number#17]
## Steps to reproduce the issue

1. install most recent Yii2 version
2. install most recent Number Control
3. The form shows the two boxes, the one linked to the model and the one used for display

## Expected behavior and actual behavior

To see only one box

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox

#### Operating System

- [X] Windows
- [X] Mac OS X

#### Libraries

- jQuery version:
- yii2-number version: 1.0.5
- yii2: 2.0.38

## Isolating the problem

- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-number without other plugins.

Code: 

```php
<p class="div-line m-r-10 m-tb-0">My minimum hourly price is </p>
<?= $form->field($user, 'price_min', ['options' => ['class' => 'w-150p m-r-10 form-group']])->widget(NumberControl::classname(), [
    'maskedInputOptions' => [
        'prefix' => '',
        'suffix' => ' USD',
        'allowMinus' => false
    ],
])->label(false); ?>
<p class="div-line m-r-10 m-tb-0">and maximum hourly price is </p>
<?= $form->field($user, 'price_max')->widget(NumberControl::classname(), [
    'maskedInputOptions' => [
        'prefix' => '',
        'suffix' => ' USD',
        'allowMinus' => false
    ],
])->label(false); ?>
```

Rendered behavior:

![Screenshot 2020-11-11 at 1 04 07 PM](https://user-images.githubusercontent.com/28290546/98771008-6fe79980-241e-11eb-9517-9a2c47ae0851.png)

**Comment by crimson-med** [comment]
This issue is still hapenning

**Comment by crimson-med** [comment]
This issue is still hapenning

**Comment by kartik-v** [comment]
Sorry - this cannot be reproduced (you can cross check with demo pages as well). Seems some styling issues specific to your environment which is forcing the hidden input to be displayed. Can you check and let know. If the issue persists, share a complete set of steps with code to reproduce. I tried using the code above and it seems to work fine.
